# Generated by Django 4.2 on 2025-02-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
