# Generated by Django 4.2 on 2025-02-11 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='address',
            new_name='description',
        ),
    ]
