# Generated by Django 4.2 on 2025-02-11 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locals',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finish_at', models.DateTimeField()),
                ('created_user_pk', models.CharField(max_length=15)),
                ('created_user_username', models.CharField(max_length=15)),
                ('created_user_email', models.CharField(max_length=15)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_shift', to='local.local')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
            },
        ),
    ]
