# Generated by Django 4.2 on 2025-02-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0004_extraitem_item_order_delete_shift_item_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
