# Generated by Django 4.2 on 2025-02-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0005_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_car_brand',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='client_car_model',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='client_car_plaque',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='client_dni',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='client_full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
