# Generated by Django 4.2 on 2025-02-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0006_order_client_car_brand_order_client_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(default=1, upload_to='order_image/'),
            preserve_default=False,
        ),
    ]
