# Generated by Django 4.2 on 2025-02-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0007_order_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_dni',
        ),
        migrations.AddField(
            model_name='order',
            name='client_email',
            field=models.EmailField(blank=True, max_length=80),
        ),
    ]
