# Generated by Django 4.2 on 2025-02-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0008_remove_order_client_dni_order_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
