# Generated by Django 4.2 on 2025-02-13 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0009_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_full_name',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_order', to='local.client'),
        ),
    ]
