# Generated by Django 4.2 on 2025-02-13 02:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0011_alter_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='client_car_brand',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_car_model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_user_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_user_username',
            field=models.CharField(max_length=100),
        ),
    ]
