# Generated by Django 4.2 on 2025-02-14 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0013_alter_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_car_brand',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_car_model',
        ),
    ]
