# Generated by Django 4.2 on 2025-02-14 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0014_remove_order_client_car_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraitem',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='extraitem',
            name='price',
            field=models.FloatField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
