# Generated by Django 4.2 on 2025-02-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0015_alter_extraitem_description_alter_extraitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='count_discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
